# Generated by Django 3.0.5 on 2020-05-23 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent0', models.BooleanField()),
                ('consent1', models.BooleanField()),
                ('consent2', models.BooleanField()),
                ('consent3', models.BooleanField()),
                ('consent4', models.BooleanField()),
                ('consent5', models.BooleanField()),
                ('consent6', models.BooleanField()),
                ('consent7', models.BooleanField()),
                ('consent8', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question1', models.CharField(max_length=1028)),
                ('question2', models.CharField(max_length=1028)),
                ('question3', models.CharField(max_length=1028)),
                ('question4', models.CharField(max_length=1028)),
                ('question5', models.CharField(max_length=1028)),
                ('drawing', models.CharField(max_length=1000000000)),
            ],
        ),
    ]
