# Generated by Django 3.0.5 on 2020-05-15 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent1', models.BooleanField()),
                ('consent2', models.BooleanField()),
                ('consent3', models.BooleanField()),
                ('consent4', models.BooleanField()),
                ('consent5', models.BooleanField()),
                ('consent6', models.BooleanField()),
                ('consent7', models.BooleanField()),
                ('consent8', models.BooleanField()),
            ],
        ),
    ]
