# Generated by Django 3.0.5 on 2020-05-30 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0003_auto_20200530_1410'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Building',
        ),
        migrations.AddField(
            model_name='response',
            name='drawing',
            field=models.CharField(default=1, max_length=1000000000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='response',
            name='question10',
            field=models.CharField(default=1, max_length=1028),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='response',
            name='question11',
            field=models.CharField(default=1, max_length=1028),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='response',
            name='question6',
            field=models.CharField(default=1, max_length=1028),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='response',
            name='question7',
            field=models.CharField(default=1, max_length=1028),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='response',
            name='question8',
            field=models.CharField(default=1, max_length=1028),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='response',
            name='question9',
            field=models.CharField(default=1, max_length=1028),
            preserve_default=False,
        ),
    ]
