# Generated by Django 3.0.5 on 2020-05-02 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0003_auto_20200502_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='question1',
            field=models.CharField(max_length=1028),
        ),
        migrations.AlterField(
            model_name='response',
            name='question2',
            field=models.CharField(max_length=1028),
        ),
        migrations.AlterField(
            model_name='response',
            name='question3',
            field=models.CharField(max_length=1028),
        ),
    ]
