# Generated by Django 3.0.5 on 2020-05-02 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0004_auto_20200502_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='drawing',
            field=models.CharField(default='hi', max_length=1000000),
            preserve_default=False,
        ),
    ]
