# Generated by Django 3.0.5 on 2020-06-24 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0004_auto_20200530_2148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='question10',
            new_name='questionA_1',
        ),
        migrations.RenameField(
            model_name='response',
            old_name='question11',
            new_name='questionA_2',
        ),
        migrations.RenameField(
            model_name='response',
            old_name='question1_1',
            new_name='questionA_3',
        ),
        migrations.RenameField(
            model_name='response',
            old_name='question1_2',
            new_name='questionA_4',
        ),
        migrations.RenameField(
            model_name='response',
            old_name='question1_3',
            new_name='questionA_5',
        ),
        migrations.RenameField(
            model_name='response',
            old_name='question1_4',
            new_name='questionB1_1',
        ),
        migrations.RenameField(
            model_name='response',
            old_name='question1_5',
            new_name='questionB1_2',
        ),
        migrations.RenameField(
            model_name='response',
            old_name='question6',
            new_name='questionB1_3',
        ),
        migrations.RenameField(
            model_name='response',
            old_name='question7',
            new_name='questionB1_4',
        ),
        migrations.RenameField(
            model_name='response',
            old_name='question8',
            new_name='questionB1_5',
        ),
        migrations.RenameField(
            model_name='response',
            old_name='question9',
            new_name='questionB1_6',
        ),
        migrations.AddField(
            model_name='response',
            name='questionB1_7',
            field=models.CharField(default=1, max_length=1028),
            preserve_default=False,
        ),
    ]
