# Generated by Django 3.0.5 on 2020-06-24 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0005_auto_20200624_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='questionB1_10',
            field=models.CharField(default=1, max_length=1028),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='response',
            name='questionB1_11',
            field=models.CharField(default=1, max_length=1028),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='response',
            name='questionB1_12',
            field=models.CharField(default=1, max_length=1028),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='response',
            name='questionB1_8',
            field=models.CharField(default=1, max_length=1028),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='response',
            name='questionB1_9',
            field=models.CharField(default=1, max_length=1028),
            preserve_default=False,
        ),
    ]
