# Generated by Django 3.0.5 on 2020-05-03 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0005_response_drawing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='drawing',
            field=models.CharField(max_length=1000000000),
        ),
    ]
