# Generated by Django 3.0.5 on 2020-07-15 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0007_auto_20200714_0918'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='drawing',
            new_name='drawing_0',
        ),
        migrations.AddField(
            model_name='response',
            name='drawing_1',
            field=models.CharField(default='hello', max_length=1000000000),
            preserve_default=False,
        ),
    ]
