# Generated by Django 3.0.5 on 2020-07-18 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0008_auto_20200715_2015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview_q',
            name='question1',
        ),
        migrations.RemoveField(
            model_name='interview_q',
            name='question2',
        ),
        migrations.AddField(
            model_name='interview_q',
            name='int_drawing_0',
            field=models.CharField(default=1, max_length=1000000000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interview_q',
            name='int_drawing_1',
            field=models.CharField(default=1, max_length=1000000000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='response',
            name='drawing_2',
            field=models.CharField(default=1, max_length=1000000000),
            preserve_default=False,
        ),
    ]
