# Generated by Django 3.0.5 on 2020-07-18 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0009_auto_20200718_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionA_1', models.CharField(max_length=1028)),
                ('questionA_2', models.CharField(max_length=1028)),
                ('questionA_3', models.CharField(max_length=1028)),
                ('questionA_4', models.CharField(max_length=1028)),
                ('questionA_5', models.CharField(max_length=1028)),
                ('questionB1_1', models.CharField(max_length=1028)),
                ('questionB1_2', models.CharField(max_length=1028)),
                ('questionB1_3', models.CharField(max_length=1028)),
                ('questionB1_4', models.CharField(max_length=1028)),
                ('questionB1_5', models.CharField(max_length=1028)),
                ('questionB1_6', models.CharField(max_length=1028)),
                ('questionB1_7', models.CharField(max_length=1028)),
                ('questionB1_8', models.CharField(max_length=1028)),
                ('questionB1_9', models.CharField(max_length=1028)),
                ('questionB1_10', models.CharField(max_length=1028)),
                ('questionB1_11', models.CharField(max_length=1028)),
                ('questionB1_12', models.CharField(max_length=1028)),
                ('drawing_0', models.CharField(max_length=1000000000)),
                ('drawing_1', models.CharField(max_length=1000000000)),
                ('drawing_2', models.CharField(max_length=1000000000)),
            ],
        ),
    ]
