# Generated by Django 3.0.5 on 2020-07-19 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0011_auto_20200719_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='questionA_1',
            field=models.CharField(max_length=1028),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='questionB1_2',
            field=models.CharField(blank=True, max_length=2048),
        ),
    ]
