# Generated by Django 3.0.5 on 2020-07-19 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0012_auto_20200719_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='questionB1_2',
            field=models.CharField(max_length=2048, null=True),
        ),
    ]
