# Generated by Django 3.0.5 on 2020-07-19 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0013_auto_20200719_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='questionB1_2',
            field=models.CharField(default=1, max_length=2048),
            preserve_default=False,
        ),
    ]
