# Generated by Django 3.0.5 on 2020-07-21 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0014_auto_20200719_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview_q',
            name='name',
            field=models.CharField(default=1, max_length=1028),
            preserve_default=False,
        ),
    ]
